### ISSUE TITLE
AQL: Dataset Modeling

### ISSUE THREAD

**Issue by cw00dw0rd** [cw00dw0rd/ArangoBnB#16]
The current dataset we intend to use is here https://www.kaggle.com/brittabettendorf/berlin-airbnb-data?select=listings_summary.csv

This may need to change if we find it isn't able to fulfill some of the features we require for the project. However, the initial investigation looks promising. 

We will need to model the data and once that is done we will update the readme to contain the working dataset.

Feel free to contribute to this as well if you have a suggested/preferred approach.

**Comment by Simran-B** [comment]
There's in fact a newer Berlin dataset from 2020-12-21: http://insideairbnb.com/get-the-data.html
It even comes with a neighborhood GeoJSON file!

**Comment by Simran-B** [comment]
## Import notes

Using the Berlin, Germany dataset from 21 December, 2020

### listings.csv

- Renamed to `listings_summary.csv`
- Mapped `id` to `_key`
- We may not need this one

### listings.csv.gz

- Unpacked as `listings.csv`
- Mapped `id` to `_key`

### reviews.csv

- Renamed to `reviews_summary.csv`
- Mapped `id` to `_key`
- We may not need this one

### reviews.csv.gz

- Unpacked as `reviews.csv`
- Mapped `id` to `_key`

### calendar.csv.gz

- Unpacked as `calendar.csv`

### neighbourhoods.csv

- Can potentially be transformed into a graph
- Should be renamed to `neighborhoods` (American English)

### neighbourhoods.geojson

- Cannot be imported with arangoimport as is, because it's a single JSON object

**Comment by cw00dw0rd** [comment]
We will need to change how the `latitude` and `longitude` values are being stored.
They will need to either be GeoJSON, an array, or stored as sub-properties.
[https://www.arangodb.com/docs/devel/arangosearch-analyzers.html#geojson](https://www.arangodb.com/docs/devel/arangosearch-analyzers.html#geojson)

I think we have enough information to make descriptive GeoJSON objects for the listings.
```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [listing.latitude, listing.longitude]
  },
  "properties": {
    "name": listing.name
  }
}
```

What do you think?

**Comment by Simran-B** [comment]
Good point, we should make it a GeoJSON Point, which moves the coordinates to a sub attribute. Not sure if there's a benefit in moving the name to the GeoJSON `properties` field. Maybe outside of ArangoDB, when exported?

**Comment by cw00dw0rd** [comment]
I don't know that there is a huge benefit to putting the name in the `properties`. Perhaps if we were creating a separate collection of just GeoJSON objects but otherwise I don't think it will make a difference.

**Comment by cw00dw0rd** [comment]
Added first dump: https://drive.google.com/drive/folders/1crMM2RRpdVgi7gkblAlAZXTvIoNNVYbT?usp=sharing

**Comment by cw00dw0rd** [comment]
Found that price above `999` were not being included, `TO_NUMBER` doesn't consider a number with a `,` as valid and thus set `1,000`+ to `0`.  Updated the query to take out the `,` and now they are included
```
FOR doc IN listings UPDATE doc WITH { price: TO_NUMBER(SUBSTRING(SUBSTITUTE(doc.price, ",",""), 1)) } IN listings
```
