### ISSUE TITLE
Analyzer geo not found after importing dump

### ISSUE THREAD

**Issue by couds** [cw00dw0rd/ArangoBnB#39]
Hi Al, I was testing the latest version of the repo, and the VUE front its not working. The API return status 500
 `AQL: unsupported SEARCH condition: 'ANALYZER' AQL function: Unable to lookup analyzer 'geo' (while optimizing plan)` 

After checking on the DB the analyzer geo do not exists, maybe I miss a step somewhere?

![image](https://user-images.githubusercontent.com/2903371/110975857-8ec05300-8360-11eb-8cc7-05a3e2c25f06.png)

Thanks

**Comment by Simran-B** [comment]
Looks like we forgot to include the `_analyzers` system collection. Can you try this dump instead?

[dump_2021-03-12](https://drive.google.com/drive/folders/1zYq3SGzdVwEkoeG9kllOWuHEh6NUMDBq?usp=sharing)

Note that you need to specify `--include-system-collections` for arangorestore in order to restore the Analyzer.

**Comment by couds** [comment]
I'm using the /dump folder from the docker. To initializate the container. I will check if that works or not and let you know. 

Thanks

**Comment by couds** [comment]
This new dump works. Thanks!
